-- Insertar 4 propiedades de ejemplo para Melvyn Liberata Torres (user_id = 1)
-- Nota: Las imágenes se deben insertar manualmente después de obtener los datos BLOB

INSERT INTO properties (user_id, titulo, descripcion, precio, tipo_operacion, tipo_propiedad, ubicacion, latitud, longitud, habitaciones, banos, area_m2, vistas, estado) VALUES
(1, 'Lujosa Casa en Playa Dorada', 'Hermosa casa de lujo ubicada en la exclusiva zona de Playa Dorada con acceso directo a la playa. Cuenta con 5 habitaciones amplias, 4 baños completos, sala de estar con vista al mar, cocina gourmet equipada, piscina privada y jardín tropical. Perfecta para familias que buscan una residencia de ensueño.', 850000.00, 'venta', 'casa', 'Playa Dorada, Santo Domingo', 18.4861, -69.9312, 5, 4, 450.00, 0, 'activa'),
(1, 'Apartamento Moderno en Zona Colonial', 'Moderno apartamento de 3 habitaciones ubicado en el corazón de la Zona Colonial. Totalmente renovado con acabados de primera calidad, piso de mármol, cocina integral, 2 baños, balcón con vista a la ciudad. Ideal para inversión o residencia. Cerca de restaurantes, tiendas y vida nocturna.', 350000.00, 'venta', 'apartamento', 'Zona Colonial, Santo Domingo', 18.4711, -69.9404, 3, 2, 120.00, 0, 'activa'),
(1, 'Terreno Comercial en Avenida Principal', 'Excelente oportunidad de inversión. Terreno comercial de 2000 m² ubicado en la Avenida Principal con alto flujo vehicular. Perfecto para desarrollar proyectos comerciales, residenciales o mixtos. Servicios básicos disponibles. Ubicación estratégica con gran potencial de rentabilidad.', 500000.00, 'venta', 'terreno', 'Avenida Principal, Santo Domingo', 18.4750, -69.9350, 0, 0, 2000.00, 0, 'activa'),
(1, 'Local Comercial en Centro Comercial Premium', 'Local comercial de 150 m² en primer piso del Centro Comercial Premium. Ideal para boutique, restaurante o cualquier negocio minorista. Excelente visibilidad, estacionamiento compartido, seguridad 24/7. Ubicación de alto tráfico con potencial de ingresos significativo. Disponible para alquiler a largo plazo.', 3500.00, 'alquiler', 'local', 'Centro Comercial Premium, Santo Domingo', 18.4800, -69.9300, 0, 1, 150.00, 0, 'activa');

-- Actualizar el contador de propiedades publicadas para Melvyn
UPDATE users SET propiedades_publicadas = 4 WHERE id = 1;
